/**
 * Kamus Indonesia — CADANGAN, bukan kamus aktif. Bahasa produk = Inggris (ADR-0016 menutup D1).
 *
 * Sengaja tetap dipelihara, bukan dihapus: `Dictionary` mewajibkan kedua bahasa memenuhi bentuk
 * yang sama, jadi berkas ini dijaga tipe dan tidak membusuk diam-diam. Itu yang membuat ADR-0016
 * tetap murah dibalik kalau D5 memasukkan Little (KG B–Grade 2), yang memang belum bisa membaca
 * Inggris — pemicu peninjauan ulang yang sudah dicatat di ADR-nya.
 *
 * Catatan: teks bebas yang ditulis anak (alasan cash-out, alasan Give) memang berbahasa Indonesia
 * apa adanya dan TIDAK terpengaruh D1. Jangan disimpan di sini.
 */
import type { Dictionary } from './types.js';

const CATEGORY_ID = {
  unsorted: 'Uang Baru',
  spend: 'Pakai',
  save: 'Simpan',
  give: 'Berbagi',
  grow: 'Bertumbuh',
} as const;

export const id: Dictionary = {
  brand: {
    name: 'Nummi',
    tagline: 'Uang kecil, kebiasaan besar.',
    positioning:
      'Nummi adalah aplikasi Parent as Banking untuk anak belajar memakai, menyimpan, berbagi dan mengelola uangnya.',
    kidApp: 'Nummi',
    kidAppShort: 'Nummi',
    parentApp: 'Nummi — untuk orang tua',
    parentAppShort: 'Nummi Ortu',
  },

  category: { little: CATEGORY_ID, middle: CATEGORY_ID, teen: CATEGORY_ID },

  common: {
    total: 'Total',
    approve: 'Setujui',
    decline: 'Tolak',
    talkAboutIt: 'Bicarakan dulu',
    markAsDone: 'Tandai selesai',
    needsOk: 'Menunggu izin',
    toDo: 'Belum dilakukan',
    done: 'Selesai',
    cancel: 'Batal',
    waitingForGrownUp: 'Menunggu orang tua',
  },

  nav: {
    home: 'Beranda',
    wallets: 'Dompet',
    add: 'Tambah',
    missions: 'Misi',
    me: 'Aku',
  },

  login: {
    title: 'Halo!',
    subtitle: 'Ketik email orang tuamu, lalu PIN-mu.',
    parentEmail: 'Email orang tua',
    parentEmailHint: 'Anak tidak perlu email sendiri. Setiap akun anak milik seorang dewasa.',
    pin: 'PIN {length} angka milikmu',
    pinHint: 'Hanya milikmu.',
    submit: 'Masuk',
    failed: 'Belum berhasil. Periksa lagi emailnya dan PIN-nya, lalu coba lagi.',
    lockedOut: 'Terlalu banyak percobaan. Tunggu {minutes} menit, lalu coba lagi.',
    askGrownUp: 'Lupa PIN? Tanya orang tuamu — mereka bisa membuatkan PIN baru.',
  },

  home: {
    greeting: 'Hai, {child}',
    totalLabel: 'Semua uangku',
    justArrived: '{amount} baru masuk!',
    sortItNow: 'Beri tugas',
    nothingToSort: 'Semua uangmu sudah punya tugas. Keren.',
    myDreams: 'Impianku',
    requestsWaiting: '{count} menunggu orang tua',
    toGo: 'kurang {amount}',
  },

  wallets: {
    title: 'Dompetku',
    target: 'Target {amount}',
    reached: 'Tercapai!',
    emptyPocket: 'Belum ada isinya',
    lockedByGrow: 'Uang di sini keluar lewat Harvest saja',
  },

  move: {
    title: 'Pindahkan uang',
    from: 'Ambil dari',
    to: 'Pindahkan ke',
    howMuch: 'Berapa?',
    preview: 'Setelah dipindahkan',
    confirm: 'Pindahkan',
    after: '{wallet} akan berisi {amount}',
    starWarning: 'Ini memotong {stars} bintangmu. Memindahkannya ke impian lain gratis.',
    needsGrownUp: 'Impian hanya bisa dibatalkan bersama orang tua.',
    nothingMovable: 'Belum ada yang bisa dipindahkan sekarang.',
    amountRequired: 'Pilih jumlahnya dulu',
    notEnough: 'Isinya tidak sebanyak itu',
    sourceLocked: 'Uang ini tidak bisa pindah sendiri',
    sameWallet: 'Pilih dua dompet yang berbeda',
    destinationNotAllowed: 'Uang tidak bisa ke sana lewat cara ini',
  },

  requests: {
    title: 'Menunggu orang tua',
    empty: 'Tidak ada yang menunggu.',
    waiting: 'Menunggu izin',
    approved: 'Sudah diizinkan — belum dilakukan',
    storyNeeded: 'Orang tuamu masih berutang cerita',
  },

  missions: {
    title: 'Misi',
    chapterOf: 'Bab {n} dari {total}',
    learn: 'Belajar',
    practice: 'Latihan',
    practiceLocked: 'Selesaikan pelajarannya dulu',
    chapterLocked: 'Selesaikan bab sebelumnya dulu',
    current: 'Kamu di sini',
    done: 'Selesai',
    starsEach: '{stars} bintang tiap pelajaran',
    weeklyGate: 'Selesaikan minggu ini untuk memakai permatamu',
  },

  kidJobs: {
    title: 'Kerjaan dari rumah',
    empty: 'Belum ada kerjaan. Tanya orang tuamu.',
    markDone: 'Sudah kukerjakan',
    waiting: 'Menunggu orang tua',
    paidInGems: '{amount} permata',
    paidInMoney: '{amount} — mendarat di Uang Baru',
    prizesTitle: 'Hadiah',
    prizesEmpty: 'Belum ada hadiah. Minta orang tuamu menambahkannya.',
    redeem: 'Tukar {cost} permata',
    yourGems: 'Permatamu {gems}',
    tooExpensive: 'Permatamu belum cukup',
    bigPrizeLocked: 'Selesaikan Bab {n} untuk hadiah besar',
    weeklyLocked: 'Selesaikan minggu ini untuk memakai permatamu',
    failed: 'Belum berhasil. Tidak ada yang berubah.',
  },

  chapter: {
    money_is_choice: 'Uang itu pilihan',
    four_jobs: 'Uang punya empat tugas',
    wants_vs_needs: 'Ingin atau butuh?',
    saving_takes_time: 'Menabung butuh waktu',
    giving: 'Berbagi',
    growing: 'Menumbuhkan uang',
  },

  me: {
    title: 'Aku',
    starsBalance: 'Bintang untuk dibelanjakan',
    starsLifetime: 'Bintang yang pernah didapat',
    gems: 'Permata',
    badges: 'Lencana',
    theme: 'Warna',
    avatarShop: 'Avatar',
    owned: 'Punyamu',
    buy: '{stars} bintang',
    cantAfford: 'Bintangmu belum cukup',
    choresLocked: 'Kumpulkan {stars} bintang untuk membuka kerjaan rumah',
    choresOpen: 'Kerjaan rumah sudah terbuka',
    bigPrizesLocked: 'Selesaikan Bab {n} untuk hadiah besar',
    cosmeticOnly: 'Bintang hanya membeli tampilan — bukan uang, bukan jalan pintas.',
    categoryColoursNeverChange: 'Warna kantong tidak pernah berubah. Itu cara kamu membaca uangmu.',
    signOut: 'Bukan kamu? Keluar',
  },

  avatar: {
    fox: 'Rubah', deer: 'Kancil', cat: 'Kucing', owl: 'Burung Hantu', dragon: 'Naga',
  },

  tracker: {
    title: 'Pantauan belajar',
    chapters: 'Bab selesai',
    starsLifetime: 'Bintang yang pernah didapat',
    gems: 'Permata',
    gateChores: 'Kerjaan dari rumah',
    gateBigPrize: 'Hadiah besar & pencapaian',
    gateWeekly: 'Memakai permata minggu ini',
    open: 'Terbuka',
    locked: 'Terkunci',
    starsToGo: 'kurang {n} bintang',
    chaptersToGo: 'Selesaikan Bab {n}',
    weeklyNoData: 'Belum ada materi mingguan',
    talkAboutIt: '{child} sedang di Bab {n} — bagus untuk ditanyakan saat makan malam.',
  },

  upsell: {
    title: 'Nummi Pro',
    price: '{amount}',
    framing: 'Sekali bayar. Dari KG B sampai Grade 9.',
    perMonth: 'Sekitar {amount} sebulan — di bawah jajan sekali.',
    cta: 'Buka Pro',
    notNow: 'Nanti saja',
    maxChildren: 'Free untuk satu anak. Pro sampai empat, dengan harga yang sama.',
    maxActiveJobs: 'Free menjalankan {n} kerjaan. Pro tanpa batas.',
    maxPrizes: 'Free menyimpan {n} hadiah. Pro tanpa batas.',
    maxDreams: 'Free menyimpan satu impian sekaligus. Pro tanpa batas.',
    strictFlexibleDial: 'Mode Ketat bagian dari Pro. Aturan proteksinya tetap gratis.',
    autoSplitEditor: 'Mengubah pembagian bagian dari Pro. Default 40/40/20 tetap gratis.',
    grow: 'Deposito, emas, dan valas bagian dari Pro. Bunga tabungan tetap gratis.',
    report: 'Rapor Literasi Finansial bagian dari Pro.',
  },

  parent: {
    dashboard: 'Beranda',
    inbox: 'Permintaan',
    send: 'Kirim uang',
    take: 'Ambil uang',
    rules: 'Aturan uang',
    noPending: 'Tidak ada yang menunggumu sekarang.',
    pendingCount: '{count} menunggumu',
    instant: 'Menyetujui berarti selesai',
    toDo: 'Menyetujui masih menyisakan tugas untukmu',
    promiseDebt: 'Kamu sudah bilang ya — belum dilakukan',
    promiseDebtHint: 'Janji yang belum kamu tepati. Ini angka yang paling penting.',
    markDone: 'Sudah saya lakukan',
    storyRequired: 'Ceritakan ke mana uangnya pergi',
    storyPlaceholder: 'Hari Minggu kami belikan beras untuk panti',
    storyMissing: 'Berbagi tidak bisa ditutup tanpa ceritanya',
    sendTitle: 'Kirim uang',
    sendSource: 'Uangnya dari mana?',
    sendNote: 'Catatan (boleh dikosongkan)',
    landsInUnsorted: 'Uangnya mendarat di Uang Baru. {child} yang menentukan tugasnya.',
    sendSubmit: 'Kirim',
    takeTitle: 'Ambil uang',
    takeReason: 'Kenapa kamu mengambilnya?',
    takeSubmit: 'Ambil',
    notificationPreview: '{child} akan melihat:',
    protectedShownNotHidden: 'Kantong terkunci sengaja tetap terlihat — supaya kamu melihat aturannya, bukan bingung ke mana perginya.',
    rulesTitle: 'Aturan uang',
    ratioTotal: 'Total {total}%',
    ratioLeftover: '{leftover}% mendarat di Uang Baru',
    modeFlexible: 'Fleksibel',
    modeFlexibleBody: 'Anakmu boleh menyortir ulang Uang Baru dan Pakai sendiri.',
    modeStrict: 'Ketat',
    modeStrictBody: 'Pembagiannya terkunci. Uang tidak bisa keluar dari tugas yang sudah diberikan.',
    enforcedOnKid: 'Ini benar-benar ditegakkan di app anakmu, bukan cuma di sini.',
    amountRequired: 'Pilih jumlahnya dulu',
    sourceRequired: 'Tandai asal uangnya',
    notEnough: 'Isinya tidak sebanyak itu',
    reasonRequired: 'Alasan wajib diisi — anakmu juga harus memberi alasan',
    protected: 'Kantong ini terlindungi',
    decisionFailed: 'Belum berhasil. Tidak ada yang berubah — periksa saldonya, lalu coba lagi.',
  },

  parentAuth: {
    title: 'Nummi untuk orang tua',
    subtitle: 'Masuk untuk melihat apa yang sedang diputuskan anakmu.',
    email: 'Email',
    password: 'Kata sandi',
    submit: 'Kirimi saya kode',
    noPassword: 'Tidak perlu kata sandi — kami kirim kode setiap kali masuk.',
    codeSent: 'Kode masuk sudah dikirim ke {email}.',
    code: 'Kode',
    codeHint: 'Berlaku sebentar saja. Cek folder spam kalau belum ada.',
    submitCode: 'Masuk',
    resend: 'Kirim kode lagi',
    badCode: 'Kode itu tidak cocok. Coba kode terbaru, atau minta yang baru.',
    tooMany: 'Terlalu sering mencoba. Tunggu beberapa menit, lalu minta kode baru.',
    failed: 'Belum berhasil. Periksa emailnya, lalu coba lagi.',
    signOut: 'Keluar',
  },

  sendSource: {
    allowance: 'Uang saku',
    thr: 'THR',
    birthday: 'Ulang tahun',
    prize: 'Hadiah',
    from_family: 'Dari keluarga',
    other: 'Lainnya',
  },

  takeLock: {
    dreamProtected: 'Impian tidak bisa ditarik kembali',
    giveProtected: 'Uang yang dijanjikan untuk berbagi tetap dijanjikan',
    growProtected: 'Bertumbuh hanya keluar lewat Harvest',
  },

  resetPin: {
    title: 'PIN baru',
    forWhom: 'Untuk {name}',
    newPin: 'PIN baru',
    hint: '{length} digit. Harus berbeda dari PIN anakmu yang lain.',
    cannotSee: 'PIN lama tidak bisa dilihat siapa pun — termasuk kamu. Yang bisa cuma menggantinya.',
    submit: 'Simpan PIN baru',
    saved: 'Selesai. PIN lama berhenti berlaku.',
    tellThem: 'Beri tahu {name} sendiri — Nummi tidak akan menampilkannya ke dia.',
  },

  requestKind: {
    cash_out: 'Tarik uang',
    give_away: 'Berbagi',
    prize: 'Hadiah',
    mission_claim: 'Misi',
    grow_in: 'Bertumbuh',
    harvest: 'Panen',
  },

  settings: {
    title: 'Pengaturan',
    allowance: 'Jadwal uang saku',
    rates: 'Bunga bankmu',
    prices: 'Harga hari ini',
    investments: 'Kelola investasi',
    allowanceOn: 'Aktif',
    allowanceOff: 'Mati',
    amount: 'Berapa',
    frequency: 'Seberapa sering',
    day: 'Hari apa',
    nextDates: 'Tiga berikutnya',
    noApprovalNeeded: 'Mendarat otomatis. Tidak perlu disetujui tiap kali.',
    landsInUnsorted: 'Mendarat di Uang Baru, sama seperti uang yang kamu kirim manual.',
    ratesTitle: 'Bunga bankmu',
    ratesHint: 'Kamu bank-nya. Ini bunga yang didapat anakmu dari deposito.',
    ratesUpsideDown: 'Tenor panjang di sini membayar lebih kecil. Deposito sungguhan menghargai kesabaran — mungkin perlu dilihat lagi.',
    oneTapApprove: 'Dengan bunga yang sudah diatur, permintaan deposito cukup disetujui sekali tap.',
    pricesTitle: 'Harga hari ini',
    goldSell: 'Emas — beli',
    goldBuyback: 'Emas — jual balik',
    spread: 'Jarak {pct}%',
    fx: 'Mata uang',
    pricesFrom: 'Per {date}',
    investmentsTitle: 'Kelola investasi',
    matured: 'Siap dipanen',
    daysLeft: '{days} hari lagi',
    startedOn: 'Mulai {date}',
    placeholderDates: 'Tanggal di seed masih placeholder — jatuh tempo diambil dari ledger sampai tanggal sungguhan masuk di S1b.',
    amountRequired: 'Tentukan nominalnya dulu',
    dayOutOfRange: 'Pilih hari yang sah (bulanan dibatasi sampai 28)',
    ratesNegative: 'Bunga tidak boleh negatif',
    ratesTooHigh: 'Bunga itu sepertinya salah ketik',
    save: 'Simpan',
    saved: 'Tersimpan. Anakmu sudah melihatnya.',
    months: '{n} bulan',
  },

  addChild: {
    title: 'Tambah anak',
    name: 'Nama',
    birth: 'Lahir',
    month: 'Bulan',
    year: 'Tahun',
    tier: 'Kelompok usia',
    tierSuggested: 'Disarankan dari usia',
    tierOverride: 'Ubah kalau kamu lebih tahu. Dan kamu memang lebih tahu.',
    pin: 'PIN',
    pinHint: '{length} digit. Anakmu mengetik ini untuk masuk — tanpa perlu nama pengguna.',
    privacy: 'Bulan dan tahun saja — tanggal persisnya tidak pernah kami minta.',
    submit: 'Tambahkan {name}',
    starterWallets: 'Dimulai dengan',
    created: 'Siap. {name} masuk pakai emailmu dan PIN ini.',
    nameRequired: 'Namanya belum diisi',
    birthMonthInvalid: 'Pilih bulan antara 1 dan 12',
    birthYearInvalid: 'Tahunnya sepertinya salah ketik',
    pinLength: 'PIN harus {length} digit',
    pinDigitsOnly: 'Angka saja',
    pinTaken: 'PIN ini sudah dipakai anggota keluarga lain. Pilih yang lain.',
    tierOnly: 'Uji awal ini untuk satu kelompok usia: {tier}, umur {min}–{max}.',
    tierOutsideScope:
      'Sekadar info: {name} di luar umur {min}–{max} yang jadi acuan uji ini. Kamu tetap bisa lanjut.',
    tierUnavailable: 'Kelompok usia itu belum dibuka di uji ini.',
  },

  jobs: {
    title: 'Kerjaan rumah',
    kind: 'Jenis pekerjaannya apa?',
    reward: 'Dibayar dengan',
    amount: 'Berapa',
    jobTitle: 'Pekerjaannya apa?',
    gemsOnly: 'Permata saja',
    whyGemsOnly: 'Membantu di rumah bukan pekerjaan berbayar. Membayarnya mengajari anak menawar harga untuk menjadi bagian dari keluarga.',
    add: 'Tambahkan',
    prizes: 'Hadiah',
    prizeTitle: 'Hadiahnya apa?',
    gemCost: 'Harganya',
    timeToEarn: 'Perlu waktu',
    weeks: 'sekitar {weeks} minggu',
    never: 'Tidak akan pernah — belum ada pekerjaan yang membayar permata',
    gemsPerWeek: '{gems} permata seminggu',
    titleRequired: 'Beri namanya',
    amountRequired: 'Tentukan nominalnya',
    moneyNotAllowed: 'Membantu di rumah dibayar dengan permata',
    costRequired: 'Tentukan harga permatanya',
    archive: 'Hapus',
    archiveHint: 'Menghapus tidak mengambil yang sudah didapat anakmu — ia cuma menghentikan klaim baru.',
  },

  jobKind: {
    family_contribution: 'Membantu di rumah',
    extra_work: 'Kerja ekstra',
    achievement: 'Pencapaian',
  },
  rewardKind: { gems: 'Permata', money: 'Uang' },
  tierName: { little: 'Kecil', middle: 'Menengah', teen: 'Remaja' },

  txn: {
    title: 'Transaksi',
    moneyIn: 'Masuk',
    moneyOut: 'Keluar',
    moved: 'Dipindah-pindah',
    net: 'Dipegang sekarang',
    count: '{count} baris',
    empty: 'Tidak ada apa-apa di rentang ini.',
    movedHint: 'Memindahkan uang antar kantong tidak membuat anakmu lebih kaya atau lebih miskin.',
    range7d: '7 hari', range30d: '30 hari', range90d: '90 hari', rangeAll: 'Semua',
    fromOutside: 'dari luar',
  },

  frequency: { weekly: 'Tiap minggu', biweekly: 'Tiap dua minggu', monthly: 'Tiap bulan' },
  weekday: {
    '0': 'Minggu', '1': 'Senin', '2': 'Selasa', '3': 'Rabu',
    '4': 'Kamis', '5': 'Jumat', '6': 'Sabtu',
  },

  sort: {
    title: 'Beri tugas untuk uangmu',
    autoSplitHint: '{spend}% Pakai / {save}% Simpan / {give}% Berbagi',
    lockedTitle: 'Orang tuamu yang mengatur pembagian ini',
    lockedBody: 'Kamu bisa melihat ke mana setiap rupiah pergi, tapi kali ini belum bisa menggesernya.',
    preview: 'Beginilah hasilnya nanti',
    confirm: 'Sudah pas',
    leftInUnsorted: '{amount} tetap di Uang Baru',
    saveFailed: 'Belum tersimpan. Tidak ada uang yang berpindah — coba lagi.',
  },

  rules: {
    strictLockedTitle: 'Uang ini sudah punya tugas',
    strictLockedBody: 'Orang tuamu yang menyimpannya di sini. Tanyakan kalau perlu diubah.',
    ratioOver100: 'Rasio melebihi 100%',
    ratioStrictMustBeExact: 'Bagikan sisa {remaining}% terakhir',
    ratioMissingDestination: 'Pilih dulu tujuan bagian ini',
    ratioGrowExcluded: 'Bertumbuh tidak bisa masuk pembagian otomatis — ia selalu butuh izinmu.',
  },

  give: {
    giveItAway: 'Berikan',
    reasonLabel: 'Kenapa yang ini? (boleh dikosongkan)',
    storyPrompt: 'Ceritakan ke {child} ke mana uangnya pergi — justru itu intinya.',
    whereMyGivingWent: 'Ke mana uang berbagiku pergi',
    title: 'Berikan',
    howMuch: 'Berapa?',
    pickCause: 'Untuk siapa?',
    notePlaceholder: 'Tulis sendiri untuk siapa',
    submit: 'Minta izin orang tua',
    sent: 'Terkirim! Orang tuamu akan menyalurkannya, lalu bercerita ke mana perginya.',
    available: '{amount} siap dibagikan',
    noStoriesYet: 'Belum ada cerita. Ceritanya muncul setelah orang tuamu menyalurkannya.',
    stillWaitingStory: 'Sudah disalurkan — menunggu ceritanya',
    amountRequired: 'Pilih jumlahnya dulu',
    notEnough: 'Itu lebih banyak dari yang bisa kamu bagikan',
    ownCauseNeedsNote: 'Tulis dulu untuk siapa',
  },

  giveCause: {
    worship: 'Tempat ibadahku',
    orphanage: 'Anak yang tidak punya orang tua',
    disaster: 'Orang yang terkena bencana',
    friend: 'Teman yang membutuhkan',
    animals: 'Hewan',
    school: 'Kotak amal sekolahku',
    own: 'Orang lain — nanti kutulis',
  },

  grow: {
    title: 'Bertumbuh',
    putIn: 'Kamu memasukkan {amount}',
    worthNow: 'Hari ini bernilai {amount}',
    youOwn: 'Kamu punya {weight}',
    pricesAsOf: 'Harga per {date}',
    whyLess: 'Kenapa jadi lebih sedikit dari yang kumasukkan?',
    whyLessBody:
      'Emas punya dua harga: harga beli, dan harga jual balik yang lebih rendah. Jaraknya sekitar {spread}%. Tidak ada yang diambil darimu — uangmu hanya butuh waktu untuk tumbuh melewati jarak itu.',
    onlyWayOut: 'Uang keluar dari Bertumbuh lewat Harvest saja',
    harvest: 'Harvest',
    harvestTo: 'Kirim ke',
    harvestLockedToSave: 'Harvest selalu mendarat di dompet Simpan.',
    matured: 'Siap dipanen',
    cashOut: 'Ambil semuanya',
    rollOver: 'Mulai lagi dengan semuanya',
    takeProfit: 'Ambil tambahannya, sisanya lanjut bekerja',
    addMoney: 'Masukkan uang',
    addMoneyFrom: 'Ambil dari',
    howMuch: 'Berapa?',
    pickInstrument: 'Mau ditaruh di mana?',
    pickTenor: 'Untuk berapa lama?',
    months: '{n} bulan',
    promisedInterest: 'Orang tuamu membayarmu {amount} di akhir',
    needsGrownUp: 'Orang tuamu harus setuju dulu.',
    submit: 'Tanya orang tuaku',
    depositBusy: 'Deposito ini masih berjalan. Tunggu sampai selesai.',
    sourceNotAllowed: 'Uang tidak bisa datang dari sana',
    notEnough: 'Isinya tidak sebanyak itu',
    amountRequired: 'Pilih jumlahnya dulu',
    tenorRequired: 'Pilih dulu berapa lama',
  },

  dream: {
    raidWarning: 'Ini memotong {stars} bintangmu. Memindahkannya ke impian lain gratis.',
  },
};
